basePath: /api/
definitions:
  models.Conditions:
    properties:
      limit:
        type: integer
      offset:
        type: integer
    type: object
  models.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      update_at:
        type: string
      username:
        type: string
    type: object
  models.UserRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a dataBase
  title: API Title
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - application/json
      description: Retrieve a list of users
      parameters:
      - description: User conditions
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.Conditions'
      produces:
      - application/json
      responses: {}
      summary: List users
      tags:
      - Users
    post:
      consumes:
      - application/json
      description: create user
      parameters:
      - description: User payload
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.UserRequest'
      responses:
        "201":
          description: User
          schema:
            additionalProperties: true
            type: object
      summary: Create
      tags:
      - Users
    put:
      consumes:
      - application/json
      description: Update a user's details
      parameters:
      - description: User details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses: {}
      summary: Update a user
      tags:
      - Users
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a user by their unique ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Delete a user
      tags:
      - Users
    get:
      consumes:
      - application/json
      description: Retrieve a user by their unique ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Get a user by ID
      tags:
      - Users
schemes:
- http
swagger: "2.0"
